env:
	export instaceStruce=UserInstace 
	export instaceVar=u
build:
	go run user_interface.go build_service.go 
go:
	export instaceStruce=UserInstace 
	export instaceVar=u
	go run user_interface.go build_service.go 

